Added my CSS animation
zero-to-mastery/CSS-Art pull request #270
Opened 2022-05-16 15:17 UTC by AryanCoder2010

*Added css animation

2022-05-16 15:36 UTC, donmarvex requested changes
Hello @AryanCoder2010 , you forgot to add your artname property. Please do so and commit the changes.

2022-05-16 15:36 UTC, donmarvex commented on include.js
> +  {
Hello @AryanCoder2010 , please add the **"artName"** property.

2022-05-17 06:32 UTC, AryanCoder2010 commented on include.js
> +  {
Thanks @donmarvex , I have created a new pull request with "artName" property.

2022-05-17 06:36 UTC, donmarvex commented on include.js
> +  {
You can just commit the changes directly to this same branch. No need for another pull request 👍

2022-05-17 06:43 UTC, donmarvex commented on include.js
> +  {
Looks cool. Great work.
Please review @sophiabrandt

2022-05-19 06:53 UTC, AryanCoder2010 commented
Kindly approve my changes.

2022-05-19 06:54 UTC, AryanCoder2010 commented
Kindly approve my changes.

2022-05-19 06:58 UTC, donmarvex approved these changes
All good here. Can successfully merge @sophiabrandt

2022-05-22 08:03 UTC, merged