Add My Animation of night view of Sky(Night Sky)
zero-to-mastery/CSS-Art pull request #315
Opened 2022-09-30 19:23 UTC by Chayandev

Added One more CSS art .
I add my new art Named Night Sky.

2022-09-30 19:32 UTC, Chayandev commented
@virtual @tigerlight @dimor @eyesonly1965 please have a look .

2022-10-02 13:08 UTC, sophiabrandt requested changes
See comment above

2022-10-02 13:08 UTC, sophiabrandt commented on include.js
> -    githubLink: 'https://github.com/MaKloudz'
It looks like you are deleting the entry from another user? Can you please look into that?

2022-10-02 13:29 UTC, Chayandev commented
No actually I just copied there writing format and on that time I pasted it
two times that's why i deleted one , i have not deleted anyone's entey , it
just a mistake , i have updated and corrected that.

On Sun, 2 Oct, 2022, 6:38 pm zero-to-mastery-bot[bot], <
***@***.***> wrote:

> 🙏 Thanks for your pull request @Chayandev <https://github.com/Chayandev>,
> The team will now review and merge this request. In the mean time why not
> check out some of the other opensource projects available, contributions
> are greatly appreciated!
>
> Some of the most popular are
>
>    - Student Resources <https://github.com/zero-to-mastery/resources>
>    - ZTM Job Board <https://github.com/zero-to-mastery/ZtM-Job-Board>
>    - Complete Web Developer Manual
>    <https://github.com/zero-to-mastery/complete-web-developer-manual>
>
> ------------------------------
> PR Statistics
> #️⃣ *PR Number:* ➕ *Line Additions:* 🗑️ *Line Deletions:*
> 315 516 5
> 📑 *Files Changed:* ⭐ *Repo Stars:* 🔱 *Total Forks:*
> 5 218 358
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/zero-to-mastery/CSS-Art/pull/315#issuecomment-1264639839>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AV5A3PSAW5ONEDCUSPTSAILWBGCORANCNFSM6AAAAAAQ2BKPGM>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-10-03 00:28 UTC, MattCSmith commented
I have just looked over this and there is indeed 5 lines being removed/replaced by this PR. 
We wont be able to merge in until the other users details are added

2022-10-10 22:12 UTC, merged